title: 生田陵の作業部屋
markdown: kramdown

# for atom feed
author:
  name: ikuta ryou
  email: ikutaryou3570@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  introduce:
    output: true
    ermalink: /introduce/:title/
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: "_introduce"
    values:
      layout: "introduce"
  - scope:
      path: "_portfolio"
    values:
      layout: "portfolio"

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
